[package]
name = "newactix"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
liquid = "0.26.4"
actix-files = "*"
serde = "1.0"
serde_derive = "1.0"



